vim.keymap.set("n", "<leader>e", function()
	if vim.bo.filetype == "oil" then
		require("oil.actions").close.callback()
	else
		vim.cmd("Oil")
	end
end, { desc = "Explorer", silent = true })
vim.keymap.set("n", "<leader>h", "<cmd>noh<cr>", { desc = "Set no hilighting", silent = true })
vim.keymap.set("i", "jk", "<esc>", { desc = "Set to normal mode", silent = true })
vim.keymap.set("v", "K", ":m '<-2<cr>gv=gv", { desc = "Moving block to top", silent = true })
vim.keymap.set("v", "J", ":m '>+1<cr>gv=gv", { desc = "Moving block to bottom", silent = true })
vim.keymap.set("v", "<", "<gv", { desc = "Untab block", silent = true })
vim.keymap.set("v", ">", ">gv", { desc = "Tab block", silent = true })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "Scroll up but keep cursor center", silent = true })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "Scroll down but keep cursor center", silent = true })
vim.keymap.set("n", "n", "nzzzv", { desc = "Move to next match but keep cursor center", silent = true })
vim.keymap.set("n", "N", "Nzzzv", { desc = "Move to prev match but keep cursor center", silent = true })
vim.keymap.set("t", "<esc><esc>", "<C-\\><C-N>", { desc = "Go to vim mode in terminal", silent = true })
vim.keymap.set("n", "<leader>t", "<cmd>term<cr>", { desc = "Open a new terminal", silent = true })
vim.keymap.set("n", "<leader>lg", "<cmd>term lazygit<cr>", { desc = "Open a lazygit inside terminal", silent = true })
vim.keymap.set("n", "<C-,>", "<C-w><", { desc = "Resize window horizontal", silent = true })
vim.keymap.set("n", "<C-.>", "<C-w>>", { desc = "Resize window horizontal", silent = true })
vim.keymap.set("n", "<C-=>", "<C-w>+", { desc = "Resize window vertical", silent = true })
vim.keymap.set("n", "<C-->", "<C-w>-", { desc = "Resize window vertical", silent = true })
vim.keymap.set("n", "ss", "<C-w>s<C-w>p", { desc = "Split window", silent = true })
vim.keymap.set("n", "sv", "<C-w>v<C-w>p", { desc = "Vertical split window", silent = true })
vim.keymap.set("n", "<leader>gg", ":copen | :silent :grep ")
vim.keymap.set("n", "<leader>pf", ":find ", { desc = "[F]ind files" })
vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Move to left" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Move to right" })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "Move to top" })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "Move to bottom" })
