foreground           =  #2b2b2b
background           =  #f5f5f5
selection-foreground =  #ffffff
selection-background =  #007acc
cursor-color         =  #000000
cursor-text          =  #ffffff

# black
palette = 0=#1f1f1f
palette = 8=#808080

# red
palette = 1=#cd3131
palette = 9=#d16969

# green
palette = 2=#107c10
palette = 10=#608b4e

# yellow
palette = 3=#b89500
palette = 11=#d7ba7d

# blue
palette = 4=#0451a5
palette = 12=#569cd6

# magenta
palette = 5=#af00db
palette = 13=#c586c0

# cyan
palette = 6=#0598bc
palette = 14=#4ec9b0

# white
palette = 7=#2b2b2b
palette = 15=#ffffff
